name: Run Playbook Engine

on:
  workflow_dispatch:  # מאפשר הרצה ידנית מתוך כפתור באתר GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m __main__ --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: |
          python main.py AAPL
